# Generated by Django 3.0.4 on 2020-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200511_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='pic',
            field=models.ImageField(default='media/avatar.png', upload_to='proimage'),
        ),
    ]
