# Generated by Django 3.0.4 on 2020-05-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200511_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='pic',
            field=models.ImageField(default='img_sample/avatar.png', upload_to='proimage'),
        ),
    ]
