# Generated by Django 3.0.4 on 2020-05-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200512_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='pic',
            field=models.ImageField(default='img_sample/tavatar.png', upload_to='proimage'),
        ),
    ]
